### ISSUE TITLE
Published to NPM without dist or "main" field in package.json

### ISSUE THREAD

**Issue by jameswomack** [jquery/PEP#202] opened 2015-07-07 23:53 UTC
Thank you for your work on this module.

This module is unusable as published on NPM. Modules should probably only be published to NPM with a require-ready version of the module published. I'd advise have an NPM prepublish step that builds and to add a "main" field in your package.json that points to dist/pep.js.

**Comment by scottgonzalez** [comment] 2015-07-08 00:01
Well, that's not entirely true; npm is a package manager for all JavaScript modules, regardless of how they're loaded.

But we should run the build first and only publish the relevant files for distribution.

**Comment by githubsheep** [comment] 2015-07-08 11:31
+1, i also need to make a prepublish step.

**Comment by jzaefferer** [comment] 2015-07-08 14:06
`main` is already in `package.json`, would have to add `files`.

**Comment by jzaefferer** [comment] 2015-10-28 15:40
Closing as a duplicate of #223.

**Closed by jzaefferer** 2015-10-28 15:40 UTC
