### ISSUE TITLE
TypeError: null is not an object (evaluating 'd.contains')

### ISSUE THREAD

**Issue by thomas-darling** [jquery/PEP#355] opened 2017-07-18 13:02 UTC
Looks like there are more bugs related to the `propagate` function.

In iOS Safari 9 and 10, it seems that the `target` in this line may be null, and since there is no check for this, an error is thrown: https://github.com/jquery/PEP/blob/master/src/dispatcher.js#L318

I'm not really sure what the correct behavior is, or why this happens... it seems to happen when one of our popup controls closes though, so it might be because the element has been removed from the DOM.

**Comment by scottgonzalez** [comment] 2017-07-18 13:52
Can you provide a reduced test case?

**Comment by thomas-darling** [comment] 2017-07-18 14:51
Not really, at least not yet - we haven't managed to replicate this in testing yet, but we get this error logged from production, so it must be happening - and it's our top trending bug, so it's not that rare :-(

**Comment by thomas-darling** [comment] 2017-07-21 16:47
Ok, so until Wednesday morning (2017-08-02 05:00 UTC) this bug can be reproduced on http://momondo.ie - after that we will deploy a patched version of PEP that checks whether `target` is null.

What seems to be happening is, that if you are on an iPhone and double-tap on one of the date selectors in the search form, then it fails with this error - and then it seems it will continue to fail on every subsequent touch after that, at least in some cases.

My guess is this is caused either by double-tab to zoom, or by some bug in Safari, maybe triggered by the appearance of the date selector on top of the touch target. Personally, I'd bet on double-tab to zoom.

Either way, this really need to be fixed.

**Comment by dmethvin** [comment] 2017-07-25 22:56
The only Safari-related problem I'm aware of is https://bugs.jquery.com/ticket/13143 which has been around for a while as you can tell.

**Comment by thomas-darling** [comment] 2017-08-01 12:57
Well, we have logged 27.000 instances of this error so far, so it is definitely there - and due to a mistake on my part, our fix was not deployed as part of our latest release, so it can actually still be consistently reproduced as described above, until our next release, which will be Tuesday, 2017-08-15 05:00 UTC.

@scottgonzalez Any chance you can take a look at this before next Tuesday?

If you don't have a Mac available for debugging, here's a guide to remote debugging iOS on Windows:
https://medium.com/@auchenberg/hello-remotedebug-ios-webkit-adapter-debug-safari-and-ios-webviews-from-anywhere-2a8553df7465
https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/52#issuecomment-299671545
(note that you can actually just ignore the `getDeviceVersion` errors)

**Comment by dmethvin** [comment] 2017-08-25 13:07
@thomas-darling if you aren't able to provide a reduced test case, is it possible for you to capture a stack trace that has some more information about the situation? Ignoring a case that shouldn't ever occur means that there's something we don't understand about the situation. If it's a bug in Safari we should report it. If it's "normal" for an event to lack a target in some cases it would be good to know what those cases are and what to do about them.

**Comment by thomas-darling** [comment] 2017-08-25 14:18
We haven't managed to reproduce it in a reduced case - we tried to, but it seems to be some strange edge case, and we just can't afford to spend more time on this issue right now.

However, if you wan't to give it a go, you should still be able to reproduce it on http://momondo.ie.
Just debug the file `bundle.dependencies.js` using Chrome remote debugging as described previously - if you enable pretty print and search for `propagate`, then you will easily find the relevant function.

Note that in our code, we have already added the condition in my pull request, so you won't actually get any errors, but you can still create a conditional breakpoint to catch it when `target` is null - it happens fairly consistently on an iPhone 6 when you double-tap on one of the date selectors in our search form.

**Comment by thomas-darling** [comment] 2017-08-25 14:58
This is where it fails:

![image](https://user-images.githubusercontent.com/6388663/29719430-488e0cbc-89b6-11e7-8112-527520451ead.png)

**Comment by thomas-darling** [comment] 2017-08-25 16:48
Please see the edits to my comment above - that's as close as I can get to the root cause for this.

I hope you can take it from there - let me know if you need me to try something anything specific, to debug this further :-)

**Comment by nadavsinai** [comment] 2017-09-28 08:26
I am reaseaching this too, is seems that taget is null because in findTarget the Y value is wrong sometimes in IOS inplace of positive values you get negative ones.

**Comment by conundrumer** [comment] 2017-11-05 04:59
I can consistently reproduce this on iOS by detecting touch events in an iframe, but ending the touch outside the iframe. I couldn't figure out how to make a reduced test case in jsfiddle though.

**Comment by conundrumer** [comment] 2017-11-16 03:37
@scottgonzalez here is the [reduced test case](https://cdn.rawgit.com/conundrumer/fa7e18d2dbfcd104cfc95e8643e9bbd4/raw/e4f689beb804f226cb7fc4670d5b98dc360f6580/pependbug.html) ([source](https://gist.github.com/conundrumer/fa7e18d2dbfcd104cfc95e8643e9bbd4)), just drag your finger out of the viewport

demonstation on iOS 10.3.3, iPhone 5s
![pep touchend demo](https://thumbs.gfycat.com/GrayVainButterfly-size_restricted.gif)

let's get #357 merged?

**Comment by apptaro** [comment] 2018-08-12 12:58
I also have this issue with PEP v0.4.3. What's the status of this issue?
@thomas-darling @conundrumer Are you guys did some own workaround for this issue?

**Comment by thomas-darling** [comment] 2018-08-12 17:45
@apptaro We just added a null check on the line where it fails - however, due to the unprofessionalism and complete lack of maintenance effort displayed here, I’ve since given up on this completely :-/

**Comment by unematiii** [comment] 2018-09-07 11:42
I too am searching for a solution to this issue (at least to the extent of silencing it). On top of the case reported earlier (move finger to address bar) I've found two other cases, where event contains "out of bounds" coordinates for `clientX` and `clientY`. 

- Safari history navigation - swipe to the left but release before the previous page is dragged in enough to get loaded (in order to prevent location change). In this case you can observe series of `touchmove` events with `clientY` to be `-300` or even lower. 
- Touching and moving the finger during the orientation change sometimes trigger `touchcancel` events with either `clientX` or `clientY` being greater then the new width/height of the viewport.

I'm thinking about two possible solutions here, either we accept the possibility of target being null and adjust the algorithm accordingly (I understand there is already a pull request that adds a null check) or adjust the `x, y` coordinates in `findTarget` to be inside the viewport boundaries.

Any thoughts are welcome...

**Comment by unematiii** [comment] 2018-09-17 09:07
@scottgonzalez Any updates on this?

**Comment by scottgonzalez** [comment] 2018-09-17 10:04
I no longer work on this project.

**Comment by unematiii** [comment] 2018-09-17 10:18
@patrickhlauke

**Comment by patrickhlauke** [comment] 2018-09-17 12:35
is anybody from the jquery side working on this, or has it been left to rot @scottgonzalez ?

**Comment by scottgonzalez** [comment] 2018-09-18 11:47
Nobody is working on this, largely due to political fallout from the JS Foundation.

**Comment by scottgonzalez** [comment] 2018-09-21 13:54
If @patrickhlauke is fine with it, I can give you write access to the repo.

**Comment by unematiii** [comment] 2018-09-25 14:02
@patrickhlauke @scottgonzalez Either that, or we could get #357 merged.

**Comment by unematiii** [comment] 2018-10-10 10:43
@scottgonzalez Thank for resolving the MPR. Could we publish this to npm?

**Comment by kutomer** [comment] 2018-10-21 18:13
any workarounds until publishing the new version to NPM?

**Comment by razorsharpshady** [comment] 2020-03-23 10:36
Hey @conundrumer , 
How can I get console errors of ipad/iphone just like the image you shared above?
![c](https://user-images.githubusercontent.com/20279966/77307975-3c85bc80-6d20-11ea-9613-b07142d2dac6.gif)

**Comment by linehammer** [comment] 2020-04-16 05:38
This error occurs when you read a property or call a method on a null object . That's because the DOM API returns null for object references that are blank. An object is expected somewhere and wasn't provided. So, you will get [null is not an object](http://net-informations.com/js/err/null.htm) error if the DOM elements have not been created before loading the script. In JavaScript , null is not an object; and won't work. You must provide a proper object in the given situation.

We can resolve this type of issues by adding an event listener that will notify us when the page is ready. Once the addEventListener is fired, the init() method can make use of the DOM elements.

```
  document.addEventListener('readystatechange', function() {
    if (document.readyState === "complete") {
      init();
    }
```

**Comment by patrickhlauke** [comment] 2021-02-10 20:36
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**

**Closed by patrickhlauke** 2021-02-10 20:36 UTC
