### ISSUE TITLE
touch-action="none" does not prevent browser's double-tap-zoom 

### ISSUE THREAD

**Issue by msegado** [jquery/PEP#211] opened 2015-07-26 23:42 UTC
In at least Chrome 43 (Android) and Safari whatever-version-my-cousin's-iPad-had (iOS), `touch-action="none"` does not prevent the browser's default double-tap zooming behavior. Minimal working example: https://jsfiddle.net/rxjpbeg8/

Not sure of the best way to implement this, but it would be great to prevent it if possible for spec compliance.

**Comment by patrickhlauke** [comment] 2015-07-27 00:02
For Chrome, the fix would be to have actual `touch-action:none` in the relevant CSS (as, since version 35, it reacts to this as an indicator that 300ms delay should be suppressed, i.e. that double-tap to zoom should be ignored - see http://patrickhlauke.github.io/touch/tests/results/#suppressing-300ms-delay)

As for iOS, it seems that in principle there's agreement to implement at least part os `touch-action` CSS in WebKit (see https://bugs.webkit.org/show_bug.cgi?id=133114 and https://bugs.webkit.org/show_bug.cgi?id=133112), but for the time being the only way to suppress double-tap to zoom there is to quite harshly `preventDefault()` things...

**Comment by msegado** [comment] 2015-07-27 01:53
@patrickhlauke Thanks for the tip; I'll give that a shot. I expect the WebKit folks would make a bunch of people happy if they enabled touch-action at some point, too =) (Plus, it would help with #151.)

Re. iOS support, it seems like it might be a good idea to have at least an opt-in polyfill in PEP that prevents-default on the second click of a double-tap... I agree it seems a bit harsh, but if it's the only option at the moment it would be nice to offer a nice clean implementation it to devs who would otherwise end up implementing that method on their own. There may be bigger fish to fry at the moment, though.

**Comment by msegado** [comment] 2015-07-27 20:36
OK - it seems that PEP can create a stylesheet for browsers with native support, but it currently checks for `window.PointerEvent` instead of `touch-action` support before doing so:

```js
var hasNativePE = window.PointerEvent || window.MSPointerEvent;
...
export function applyAttributeStyles() {
  if (hasNativePE) {
  ...
```

I think it would make more sense to check for the latter since some browsers (e.g. Chrome, hopefully future Safari) only support `touch-action` natively but don't yet support `window.PointerEvent`. Something like `(typeof document.createElement('div').style.touchAction === 'string')` seems to do the trick, though I make no guarantees!

Of course, this will be moot if #151 lands.

**Comment by arschmitz** [comment] 2015-07-30 16:41
We decided in the meeting today to switch to using the style attribute which will remove this whole file.

**Comment by msegado** [comment] 2015-07-30 17:49
@arschmitz Awesome - thanks for your work on this!

Keep in mind that using the style attribute still won't resolve this on Safari, though - that seems like it will require a javascript solution for now, perhaps with an opt-in or opt-out flag since it will likely need to prevent-default.

For now though, it's probably a good idea to just add this as a limitation in the Readme =)

**Comment by arschmitz** [comment] 2015-07-30 17:51
@msegado we are not attempting to implement this as a feature. just fixing the bug you noticed about properly supporting native.

**Comment by msegado** [comment] 2015-07-30 18:02
@arschmitz That seems fine; I have a workaround in place for Safari that seems to be doing the trick. (Do keep in mind though that it should be listed as a limitation on the Readme, since preventing browser zooms is part of the spec for both `touch-action="none"` and `touch-action="manipulation"`.)

**Comment by jzaefferer** [comment] 2015-10-28 15:35
Closing as a duplicate of #151 - at least as far as commented on above.

**Closed by jzaefferer** 2015-10-28 15:35 UTC
