### ISSUE TITLE
PEP skipping first event (pointerdown)

### ISSUE THREAD

**Issue by niclaslindberg** [jquery/PEP#292] opened 2016-06-02 07:21 UTC
I have noticed that PEP skips the fist event sometimes. In my cases it happened after clearing a canvas or when showing a Boostrap Modal for the second time (buttons event handlers were only invoked the second time). 

The stupid fix below removes the problem but I'm sure it's not the way to go.

```javascript
  mousedown: function(inEvent) {
            if (!this.isEventSimulatedFromTouch(inEvent)) {
                var p = mouse__pointermap.get(this.POINTER_ID);
                var e = this.prepareEvent(inEvent);
                if (!HAS_BUTTONS) {
                    e.buttons = BUTTON_TO_BUTTONS[e.button];
                    if (p) { e.buttons |= p.buttons; }
                    inEvent.buttons = e.buttons;
                }
                mouse__pointermap.set(this.POINTER_ID, inEvent);
                p=undefined; // The error occurs when p is defined.
                mouse__pointermap.delete(this.POINTER_ID); //Clear it
                if (!p) {
                    _dispatcher.down(e);
                } else {
                    _dispatcher.move(e);
                }
            }
        },
```

**Comment by bethge** [comment] 2016-06-02 07:31
Could you create an example demonstrating the issue on e.g. http://jsbin.com?

Also, which browser are you using?

**Comment by niclaslindberg** [comment] 2016-06-02 15:12
Hi.

https://jsbin.com/gagifa/3/edit

First time you click the button an alert is shown. The second time 
nothing happens. The third time the alert shows again.

// Niclas

**Comment by patrickhlauke** [comment] 2016-06-02 15:19
I'll have a guess and say it's because PEP loses track of the pointer, as after `pointerdown` the mouse is moved over to the alert, so it never sees the `pointerup`. after you dismiss the alert, next time you press the button PEP likely is still in a state where it's expecting the `up` so it can fire `pointerup` to finish the sequence that was started with the original `pointerdown`.

As a workaround for now: if you change it to react to `pointerup`, it works as it should (more generally, you may as well just listen to `click`, but that may just be the case for the simplified test case)

**Comment by scottgonzalez** [comment] 2016-06-02 15:49
This appears to be a duplicate of #279.

**Closed by scottgonzalez** 2016-06-02 15:49 UTC
